FROM rocker/r-base:4.4.0

RUN apt-get update

RUN R -e 'install.packages("renv")'
RUN mkdir /test
WORKDIR /test

COPY renv.lock /test
RUN R -e 'renv::restore()'

COPY *.R /test
CMD ["R", "-f", "main.R"]
